### ISSUE TITLE
Cleanup cloud stacks

### ISSUE THREAD

**Issue by rv2e** [datacamp/sqlwhat-viewer#9]
This project uses EB now, we should then remove the stack on Heroku (it becomes useless). 
Also we should link the EB url to a datacamp domain using Route53: `sqlwhat-viewer.datacamp.com`.

**Comment by machow** [comment]
working on `sqlwhat-viewer.datacamp.com`, would it be quick to change to `ast-viewer.datacamp.com`. Sorry, I can do it down the road if it's straightforward 😬.

**Comment by rv2e** [comment]
http://ast-viewer.datacamp.com/static/index.html
